import { Inter } from "next/font/google";
import "./globals.css";
import AppWrapper from "../components/AppWrapper";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kindlegate Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white overflow-x-hidden`}>
        <NextUIProvider>
          <AppWrapper>
            {children}
          </AppWrapper>
        </NextUIProvider>
      </body>
    </html>
  );
}
