import { Inter } from "next/font/google";
import "./globals.css";
import AppWrapper from "../components/AppWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kindlegate Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className={`${inter.className} bg-white`}>
              <AppWrapper>
              {children}
              </AppWrapper>
          </body>
    </html>
  );
}
